services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    restart: on-failure
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    command:
      [
        '-path',
        '/migrations',
        '-database',
        'postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable',
        'up',
      ]

  api:
    image: go-todo-api
    restart: always
    depends_on:
      - db
      - migrate
    ports:
      - '${APP_PORT}:8080'
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSL_MODE: ${DB_SSL_MODE}

volumes:
  postgres_data:
